config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  resources :properties do
    collection do
      get :auction
      get :featureds, to: 'properties#featured'
      get 'wishlist/:id', to: 'properties#wishlist', as: 'wishlist'
      post :checkout_bid
    end
    member do
      get 'reviews', to: 'properties#reviews'
      delete 'reviews/:rate_id', to: 'properties#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end

  resources :users, only: [:show]
  resources :landing_pages, only: [:show]
  resources :inquiries
  resources :feedbacks, only: [:create]
  resources :reports, only: [:create]
  resources :schedule_visits, only: [:create]
  resources :confirmations, path: 'konfirmasi', only: [:new, :create]

  get 'map',                          to: 'properties#map',             as: 'map'
  get 'list',                         to: 'properties#list',            as: 'list'
  get 'package',                      to: 'publics#package',            as: 'package'
  get 'get_societies',                to: 'publics#get_societies',      as: 'get_societies'

  get 'get_assets',                   to: 'xhrs#get_assets',            as: 'get_assets'
  get 'get_assets_property',          to: 'xhrs#get_assets_property',   as: 'get_assets_property'
  post 'save_assets_property',        to: 'xhrs#save_assets_property',  as: 'save_assets_property'
  get 'get_categories',               to: 'publics#get_categories',     as: 'get_categories'
  get 'cities_tag',                   to: 'publics#cities_tag',         as: 'cities_tag'
  get 'cities',                       to: 'xhrs#cities',                as: 'cities'
  get 'subdistricts',                 to: 'xhrs#subdistricts',          as: 'subdistricts'
  get 'village',                      to: 'xhrs#village',               as: 'village'
  get 'area',                         to: 'xhrs#area',                  as: 'area'
  get 'get_by_city',                  to: 'xhrs#get_by_city',           as: 'get_by_city'
  get 'get_properties_search',        to: 'xhrs#get_properties_search', as: 'get_properties_search'
  get '/get_detail_profile_property', to: 'xhrs#get_detail_properties', as: 'get_detail_profile_property'
  get '/label_packages',              to: 'xhrs#label_packages',        as: 'label_packages'

  get "autocomplete_region",          to: "xhrs#autocomplete_region"
  get "autocomplete_auction_region",  to: "xhrs#autocomplete_auction_region"

  get 'region/:id',                   to: 'landing_pages#region',       as: 'region'
  get 'contact',                      to: 'publics#contact',            as: 'contact'
  get 'help',                         to: 'publics#help',               as: 'help'
  put 'daftar-paket/:id',             to: 'publics#add_package',        as: 'add_package'
  
  get "sitemap.xml" => "sitemaps#index", format: "xml",                 as: 'sitemap'

  resources :blog_infos, only: [:index, :show], path: 'blog' do
    member do
      get :category
    end
    collection do
      get :results
    end
  end
  resources :agents
  resources :xhrs do
    collection do
      get :get_categories
      get :get_facilities
    end
  end

  namespace :backend do
    # The Role
    resources :roles, except: :show do
      patch 'change', on: :member
      resources :sections, controller: 'role_sections', only: :none do
        collection do
          post :create
          post :create_rule
          post :create_field
        end

        member do
          put :rule_on
          put :rule_off

          delete :destroy
          delete :destroy_rule
        end
      end
    end

    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :agents do
      collection do
        post :do_multiple_act
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_user_packages do
      member do
        patch '/confirmations', to: 'order_user_packages#confirmations'
      end
      collection do
        post '/multiple_confirmations', to: 'order_user_packages#multiple_confirmations'
      end
    end
    resources :developers do
      collection do
        post :do_multiple_act
      end
    end
    resources :properties do
      collection do
        get :pending
        post :do_multiple_act
        get :import, to: 'properties#import'
        post :do_import, to: 'properties#do_import'
        post :import, to: 'properties#do_import'
      end
    end
    resources :auction_properties do
      collection do
        post :do_multiple_act
      end
    end
    resources :property_types do
      collection do
        post :do_multiple_act
      end
    end
    resources :asset_facilities do
      collection do
        post :do_multiple_act
      end
    end
    resources :locations do
      collection do
        post :do_multiple_act
      end
    end
    resources :supporteds do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :feedbacks do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :sold_reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :blog_infos do
      collection do
        post :do_multiple_act
      end
    end
    resources :category_blog_infos do
      collection do
        post :do_multiple_act
      end
    end
    resources :regions
    resources :landing_pages
    resources :web_settings

    resources :confirmations do
      collection do
        post :do_multiple_act
      end
    end

    resources :order_packages do
      collection do
        post :do_multiple_act
      end
    end
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members do
      member do
        put :upgrade
      end
    end
    resources :agents, only: [:edit, :update, :show]
    resources :wishlists
    resources :inquiries
    resources :notifications
    resources :properties do
      member do
        put :renew
      end
      collection do
        post :do_report_sold
      end
    end
    resources :sold_reports
    resources :order_packages
    resources :packages do
      collection do
        get :invoices
      end
      member do
        get :invoice
      end
    end
  end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
	before_filter :prepare_counts!

	add_breadcrumb "Dashboard", :backend_dashboard_path

	def dashboard
	end

	private
		def prepare_counts!
	  end
end

app/controllers/userpage/home_controller.rb
class Userpage::HomeController < Userpage::ApplicationController
	add_breadcrumb "Dashboard", :userpage_dashboard_path

	def dashboard
	end

end

app/views/shareds/home/_agent_list.html.erb
<section class="agent-list-home">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-property">
          <h2>List Agen Terverifikasi</h2>
          <div class="title-highlight"></div>
        </div>
        <div class="ads">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8140461930329474"
               data-ad-slot="3062552949"
               data-ad-format="auto"></ins>
          <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
          <br>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div id="slide-agent-listing" class="owl-carousel owl-theme">
            <% @agents.each do |resource| %>
              <div class="item">
                <div class="box-image-avatar">
                  <%= link_to user_path(resource) do %>
                    <%= image_tag "#{resource.try(:profile).try(:avatar).url(:small)}", title: 'Situs jual rumah di Indonesia', alt: 'Situs jual rumah di Indonesia' %>
                  <% end %>
                </div>
                <div class="name-agent">
                  <%= link_to user_path(resource) do %>
                    <%= resource.try(:profile).try(:full_name) %>
                  <% end %>
                </div>
                <div class="name-group">
                  <i class="fa fa-map-marker"></i> Area : <%= resource.agent_info.specialist_area %>
                  <br>
                  <i class="fa fa-home"></i> Spesialis : <%= resource.agent_info.specialist_property %>
                </div>
              </div>
            <% end %>
          </div>
          <%= link_to 'Selengkapnya', agents_path, class: 'btn btn-info btn-more' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shareds/home/_blog_list.html.erb
<div class="bg-white">
  <div class="container">
    <div class="row blog-home-default">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-12">
                <div class="title-property">
                  <h2>Berita Terbaru</h2>
                  <div class="title-highlight"></div>
                </div>
              </div>
            </div>
            <div class="row">
              <% @blog_infos.each_with_index do |blog_infos, index| %>
                <% cache ["home_latest_blogs_#{blog_infos.id}_#{blog_infos.updated_at.to_time.to_i}"] do %>
                  <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="blog-info-three">
                      <div class="body-info-three">
                        <div class="image-info-three">
                          <%= image_tag blog_infos.cover.url(:medium), alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                          <div class="date">
                            <span>
                              <i class="fa fa-calendar"></i> <%= blog_infos.created_at.strftime("%B, %d, %Y") %>
                            </span>
                          </div>
                        </div>
                        <div class="desc-info-three">
                          <%= link_to blog_infos.title, blog_info_path(blog_infos), class: 'title' %>
                          <div class="description">
                            <%= truncate(strip_tags(blog_infos.description), length: 100, omission: '...') %>
                            <%= link_to 'more', blog_info_path(blog_infos) %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-12">
            <div class="title-property">
              <h2>Event</h2>
              <div class="title-highlight"></div>
            </div>
          </div>
        </div>
        <div class="blog-rumahdaku-sidebar">
          <div class="listing-info-sidebar-wrapper bdr-sidebar-right">
            <% @event.each_with_index do |event, index| %>
              <% cache ["home_latest_events_#{event.id}_#{event.updated_at.to_time.to_i}"] do %>
                <div class="list-info-blog">
                  <div class="images-blog-wrapper">
                    <div class="images-blog">
                      <%= image_tag event.cover.url(:thumb), alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                    </div>
                  </div>
                  <div class="info-blog-wrapper">
                    <div class="category">
                      <%= event.try(:category_blog_info).try(:name) %>
                    </div>
                    <%= link_to event.title, blog_info_path(event), class: 'title' %>
                    <div class="comments">
                      <i class="fa fa-calendar"></i> <%= event.created_at.strftime("%I:%M %B, %d, %Y") %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="ads">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <!-- home-bottom-sidebar-rumahdaku -->
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-8140461930329474"
               data-ad-slot="8364370140"
               data-ad-format="auto"></ins>
          <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shareds/home/_carousel.html.erb
<section class="page-wrapper slider-property-wrapper">
  <section class="main-slider">
    <div class="tp-banner-container">
      <div class="tp-banner">
        <ul>
          <% @setting.galleries.each do |gallery| %>
            <% cache ["home_carousel_#{gallery.id}_#{gallery.updated_at.to_time.to_i}"] do %>
              <li data-transition="slideleft" data-slotamount="1" data-masterspeed="1000" data-thumb="<%= image_url gallery.file.url(:small) %>" data-saveperformance="off" data-title="<%= gallery.title %>">
                  <%= image_tag gallery.file.url, data: { bgposition: "center top", bgfit: "cover", bgrepeat: "no-repeat" } %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </section>
  <%= form_for :search, url: properties_path, html:{id: 'property-search', name: 'search'}, method: 'get' do %>
    <div class="container">
      <div class="row">
        <div class="col-md-12 box-slider-logo">
          <div class="box-logo-slider">
            <%= image_tag 'logo-center.png', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
          </div>
          <h1 class="box-search-slider-title">
            Situs jual beli sewa dan gadai property di seluruh Indonesia
          </h1>
          <div class="box-search-slider">
            <div class="input-group">
              <span class='search-form'>
                <%= autocomplete_field_tag :region_display_name, "", autocomplete_region_path, placeholder: "Cari Berdasarkan Lokasi ...", class: 'form-control input-search-lg', value: params[:region_display_name] %>
              </span>
              <span class="input-group-btn">
                <button class="btn btn-default btn-lg btn-search-lg no-border" type="submit"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/shareds/home/_category.html.erb
<% cache("home_categories", expires_in: 5.day) do %>
  <section class="point-information-property-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="box-point-infomation-property">
            <div class="category-property-point">
              <%= link_to properties_path(category: 'Dijual'), class: "box-point" do %>
                <div class="icon">
                  <%= image_tag 'dijual.png', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                </div>
              <% end %>
            </div>
            <div class="category-property-point">
              <%= link_to properties_path(category: 'Disewa'), class: "box-point" do %>
                <div class="icon">
                  <%= image_tag 'disewa.png', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                </div>
              <% end %>
            </div>
            <div class="category-property-point">
              <%= link_to properties_path(category: 'Digadai'), class: "box-point" do %>
                <div class="icon">
                  <%= image_tag 'digadai.png', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                </div>
              <% end %>
            </div>
            <!-- <div class="category-property-point">
              <%= link_to properties_path(category: 'Dilelang'), class: "box-point" do %>
                <div class="icon">
                  <%= image_tag 'dilelang.png', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
                </div>
              <% end %>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/shareds/home/_group_partner.html.erb
<section class="section group-partner">
	<div class="container">
		<div class="line-through">
			<p><span>Supported By</span></p>
		</div>
		<div id="media" class="carousel carousel_supporteds slide media-carousel">
			<div class="carousel-inner">
				<% @supporteds.each do |f| %>
					<% cache ["supporteds_#{f.id}_#{f.updated_at.to_time.to_i}"] do %>
						<div class="supporteds-item col-md-2">
							<%= image_tag "#{f.logo.url(:small)}", alt: '#{ f.title }', class: 'img-responsive', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
						</div>
					<% end %>
				<% end %>
			</div>
			<a data-slide="prev" href="#media" class="left carousel-control">‹</a>
			<a data-slide="next" href="#media" class="right carousel-control">›</a>
		</div>
	</div>
</section>

app/views/shareds/home/_paralax.html.erb
<section class="parallax">
	<div class="ha-bg-parallax text-center">
		<div class="ha-parallax-body">
			<div class="ha-content ha-content-whitecolor">
				"PROPEDIA is a market / Indonesia's largest online mall that lets individuals and business owners in Indonesia to open and manage their online store is easy and free."
			</div>
			<div class="ha-parallax-divider-wrapper">
				<span class="ha-diamond-divider-md img-responsive"></span>
			</div>
			<div class="ha-heading-parallax">CEO PROPEDIA</div>
		</div>
	</div>
</section>

app/views/shareds/home/_popular_list.html.erb
<section class="location-featured-wrapper bg-grey-smooth">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="title-one-top">
          Iklan terpopuler
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="listing-property">
          <% @properties.each do |resource| %>
            <%= render 'properties/property', resource: resource unless resource.the_auction? %>
            <%= render 'properties/property_auction', resource: resource if resource.the_auction? %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="ads">
        <br>
        <br>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- home-middle-rumahdaku -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-8140461930329474"
             data-ad-slot="5550504545"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>
    </div>
  </div>
</section>

app/views/shareds/home/_popular_locations.html.erb
<section class="location-featured-wrapper bg-grey">
  <div class="container">
    <div class="row">
      <div class="ads">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- home-top-rumahdaku -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-8140461930329474"
             data-ad-slot="6108907748"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <br>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="title-one-top">
          Dibawah ini adalah beberapa lokasi pilihan yang terkenal di indonesia, antara lain!
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
      	<% @regions.each do |region| %>
          <% cache ["home_region_#{region.id}_#{region.updated_at.to_time.to_i}"] do %>
        		<% region_display_name = "#{region.try(:name)}, #{region.try(:parent).try(:name)}" %>
  	        <div class="col-md-6 col-sm-6">
  	          <div class="box-location-point">
  	            <div class="box-image-location-wrapper">
  	              <div class="box-image-location">
  	                <%= image_tag region.image.url(:medium), class: 'img-responsive', alt: 'Situs jual rumah di Indonesia', title: 'Situs jual rumah di Indonesia' %>
  	              </div>
  	            </div>
  	            <div class="box-desc-location">
  	              <div class="title">
  	                <%= link_to properties_path(region_display_name: region_display_name) do %>
  	                	<%= region.name %>, <%= region.root.name if region.root.present? %></a>
  	                <% end %>
  	              </div>
  	              <div class="description">
                    <%= truncate strip_tags(region.description.to_s), length: 50 if region.description.present? %>
  	              </div>
  	            </div>
  	          </div>
  	        </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shareds/home/_testimonials.html.erb
<section class="section green">
	<div class="container">
		<div class="row">
			<h2 align="center">WHAT DRIVES US</h2>
			<div class="col-md-12" data-wow-delay="0.2s">
				<div class="carousel slide" data-ride="carousel" id="quote-carousel">
					<ol class="carousel-indicators">
						<% @testimonials.each_with_index do |testimonial,index| %>
							<% cache ["ava_testimonials_#{testimonial.id}_#{testimonial.updated_at.to_time.to_i}"] do %>
								<li data-target="#quote-carousel" data-slide-to="0" class="<%= 'active' if index == 1 %>">
									<%= image_tag "#{testimonial.try(:user).try(:profile).try(:avatar).url(:small)}", class: 'img-responsive' if testimonial.user.present? %>
								</li>
							<% end %>
						<% end %>
					</ol>

					<div class="carousel-inner text-center">
						<% @testimonials.each_with_index do |testimonial,index| %>
							<% cache ["testimonials_#{testimonial.id}_#{testimonial.updated_at.to_time.to_i}"] do %>
								<div class="item <%= 'active' if index == 1 %>">
									<blockquote>
										<div class="row">
											<div class="col-sm-8 col-sm-offset-2">
												<p><%= testimonial.message.html_safe if testimonial.message.present? %></p>
												<small>
													@<%= testimonial.email %> | <%= testimonial.name %>
												</small>
											</div>
										</div>
									</blockquote>
								</div>
							<% end %>
						<% end %>
					</div>

					<a data-slide="prev" href="#quote-carousel" class="left carousel-control">
						<i class="fa fa-chevron-left"></i>
					</a>
					<a data-slide="next" href="#quote-carousel" class="right carousel-control">
						<i class="fa fa-chevron-right"></i>
					</a>
				</div>
			</div>
		</div>
		</div>
	</div>
</section>